also_exclude:
  - "*/dist/**/*"

restylers:
  # Disable other json formatters (using prettier-json)
  - "!clang-format"
  - "!jq"

  # It's important to align the yaml examples in the README nonstandardly
  - prettier-markdown:
      include:
        - "**/*.md"
        - "!README.md"

  - "*"
