also_exclude:
  - "*/dist/**/*"
  - "run/suggest-test-files/**/*"

restylers:
  # Disable other json formatters (using prettier-json)
  - "!clang-format"
  - "!jq"

  # This is a bug in the manifest, I'd say
  - prettier:
      include:
        - "run/src/**/*.ts"

  - whitespace:
      include:
        - "**/*"
        - "!run/src/parse-git-patch.test.ts" # significant whitespace, for now

  - "*"
