also_exclude:
  - "*/dist/**/*"

restylers:
  # Disable other json formatters (using prettier-json)
  - "!clang-format"
  - "!jq"

  # This is a bug in the manifest, I'd say
  - prettier:
      include:
        - "run/src/**/*.ts"

  - "*"
