# Copyright (C) 2024 Patrick Brisbin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
name: Create files for demoing (or testing) Restyled
author: pbrisbin

inputs:
  channel:
    description: restylers.yaml channel to base things on
    default: stable
  options:
    description: Additional options to pass to generation
    required: false

outputs:
  manifest:
    description: "Location the channel manifest was downloaded to"
    value: ${{ steps.download.outputs.manifest }}

runs:
  using: composite
  steps:
    - shell: bash
      id: download
      run: |
        # Download manifest
        curl -sSf -L -o "$MANIFEST" "$MANIFEST_URL"
        echo "manifest=$MANIFEST" >>"$GITHUB_OUTPUT"
      env:
        MANIFEST: "/tmp/restylers-${{ inputs.channel }}.yaml"
        MANIFEST_URL: "https://docs.restyled.io/data-files/restylers/manifests/${{ inputs.channel }}/restylers.yaml"

    - shell: bash
      run: |
        # Generate test files
        "$GITHUB_ACTION_PATH"/bin/generate-test-files \
          --manifest "$MANIFEST" $OPTIONS
      env:
        MANIFEST: ${{ steps.download.outputs.manifest }}
        OPTIONS: |
          ${{ env.RUNNER_DEBUG && '--verbose ' }}${{ inputs.options }}

    - shell: bash
      run: |
        # Add test files to git
        git config --global user.email "commits@restyled.io"
        git config --global user.name "Restyled.io"

        if [[ ! -d ".git" ]]; then
          git config --global init.defaultBranch main
          git init .
        fi

        git add .
        git commit -m "Add demo files"
