name: Create files for demoing (or testing) Restyled
author: pbrisbin

inputs:
  channel:
    description: restylers.yaml channel to base things on
    default: stable
  limit:
    description: only generate for a random number of Restylers
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        curl -sSf -L -o "$MANIFEST" "$MANIFEST_URL"
      env:
        MANIFEST: "/tmp/restylers-${{ inputs.channel }}.yaml"
        MANIFEST_URL: "https://docs.restyled.io/data-files/restylers/manifests/${{ inputs.channel }}/restylers.yaml"

    - shell: bash
      run: |
        "$GITHUB_ACTION_PATH"/bin/generate-test-files "MANIFEST"
      env:
        LIMIT: ${{ inputs.limit }}
        MANIFEST: "/tmp/restylers-${{ inputs.channel }}.yaml"

    - shell: bash
      run: |
        # Create git repository
        if [[ -d .git ]]; then
          echo "actions/setup-demo cannot be used in an existing checkout" >&2
          exit 1
        fi

        git init .
        git config user.email "commits@restyled.io"
        git config user.name "Restyled"
        git add .
        git commit -m "Add demo files"
