name: Create files for demoing (or testing) Restyled
author: pbrisbin

inputs:
  channel:
    description: restylers.yaml channel to base things on
    default: stable
  options:
    description: Additional options to pass to generation
    required: false

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        # Download manifest
        curl -sSf -L -o "$MANIFEST" "$MANIFEST_URL"
      env:
        MANIFEST: "/tmp/restylers-${{ inputs.channel }}.yaml"
        MANIFEST_URL: "https://docs.restyled.io/data-files/restylers/manifests/${{ inputs.channel }}/restylers.yaml"

    - shell: bash
      run: |
        # Generate test files
        "$GITHUB_ACTION_PATH"/bin/generate-test-files \
          --manifest "$MANIFEST" $OPTIONS
      env:
        MANIFEST: "/tmp/restylers-${{ inputs.channel }}.yaml"
        OPTIONS: |
          ${{ env.RUNNER_DEBUG && "--verbose "}}${{ inputs.options }}

    - shell: bash
      run: |
        # Add test files to git
        git config --global user.email "commits@restyled.io"
        git config --global user.name "Restyled.io"

        if [[ ! -d ".git" ]]; then
          git config --global init.defaultBranch main
          git init .
        fi

        git add .
        git commit -m "Add demo files"
