name: Restyle
description: Run the restyle CLI on changed files in a PR
author: pbrisbin

inputs:
  paths:
    description: |
      New-line separated paths to restyle, default is paths changed in the PR
    required: false
  github-token:
    description: "Token used to query for PR details"
    default: ${{ github.token }}
  show-patch:
    description: "Log the patch produced by Restyled with git format-patch"
    default: true
  show-patch-command:
    description: |
      Log a copy/paste-able command to apply the patch produced by Restyled with
      git-am
    default: true
  fail-on-differences:
    description: "Exit non-zero if differences were created"
    default: false
  committer-email:
    description: "Email used for Restyled commits"
    default: "commits@restyled.io"
  committer-name:
    description: "Name used for Restyled commits"
    default: "Restyled.io"
  log-level:
    description: "Set `restyle`'s `LOG_LEVEL`"
    default: "info"
  log-format:
    description: "Set `restyle`'s `LOG_FORMAT`"
    default: tty
  log-breakpoint:
    description: "Set `restyle`'s `LOG_BREAKPOINT`"
    default: 200
  manifest:
    description: "Path to pass as `--manifest` to `restyle`"
    required: false
  dry-run:
    description: "Pass `--dry-run` to `restyle`"
    default: false

outputs:
  differences:
    description: "`true` if differences were created by restyling"
  git-patch:
    description: "The restyle commits, formatted for use with `git am`"
  restyled-base:
    description: "The base branch to use if opening fixes as a new PR"
  restyled-head:
    description: "The head branch to use if opening fixes as a new PR "
  restyled-title:
    description: "The title to use if opening fixes as a new PR"
  restyled-body:
    description: "The body to use if opening fixes as a new PR"

runs:
  using: "node20"
  main: "dist/index.js"
