name: Restyle
description: Run the restyle CLI on changed files in a PR
author: pbrisbin

inputs:
  paths:
    description: |
      New-line separated paths to restyle, default is paths changed in the PR
    required: false
  github-token:
    description: "Token used to query for PR details"
    default: ${{ github.token }}
  show-patch:
    description: "Log the patch produced by Restyled with git format-patch"
    default: true
  show-patch-command:
    description: |
      Log a copy/paste-able command to apply the patch produced by Restyled with
      git-am
    default: true
  committer-email:
    description: "Email used for Restyled commits"
    default: "commits@restyled.io"
  committer-name:
    description: "Name used for Restyled commits"
    default: "Restyled.io"
  debug:
    description: "Past `--debug` to `restyle`"
    default: false
  dry-run:
    description: "Pass `--dry-run` to `restyle`"
    default: false
  fail-on-differences:
    description: "Pass `--fail-on-differences` to `restyle`"
    default: false
  image-cleanup:
    description: "Pass `--image-cleanup` to `restyle`"
    default: false
  manifest:
    description: "Path to pass as `--manifest` to `restyle`"
    required: false
  no-commit:
    description: "Pass `--no-commit` to `restyle`"
    default: false
  no-pull:
    description: "Pass `--no-pull` to `restyle`"
    default: false

outputs:
  success:
    description: "`true` if `restyle` ran successfully (differences or not)"
  differences:
    description: "`true` if differences were created by restyling"
  git-patch:
    description: "The restyle commits, formatted for use with `git am`"
  restyled-base:
    description: "The base branch to use if opening fixes as a new PR"
  restyled-head:
    description: "The head branch to use if opening fixes as a new PR "
  restyled-title:
    description: "The title to use if opening fixes as a new PR"
  restyled-body:
    description: "The body to use if opening fixes as a new PR"

runs:
  using: "node20"
  main: "dist/index.js"
