name: Restyle
description: Run the restyle CLI on changed files in a PR
author: pbrisbin

inputs:
  log-breakpoint:
    description: "LOG_BREAKPOINT"
    default: 200
  log-format:
    description: "LOG_FORMAT"
    default: tty
  log-level:
    description: "LOG_LEVEL"
    default: "info"
  github-token:
    description: "GITHUB_TOKEN"
    default: ${{ github.token }}
  committer-email:
    description: "Email used for Restyled commits"
    default: "commits@restyled.io"
  committer-name:
    description: "Name used for Restyled commits"
    default: "Restyled.io"

outputs:
  differences:
  git-patch:
  restyled-base:
  restyled-head:
  restyled-title:
  restyled-body:

runs:
  using: "node20"
  main: "dist/index.js"
