# Copyright (C) 2025 Patrick Brisbin
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: Setup the Restyler CLI
author: pbrisbin

inputs:
  tag:
    description: "Release tag to install, if empty latest is used"
    required: false
  github-token:
    description: "GitHub token used for gh invocations"
    default: "${{ github.token }}"

outputs: {}

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        gh_release() {
          gh --repo restyled-io/restyler release "$@"
        }

        os=$(uname -s | tr '[:upper:]' '[:lower:]')
        arch=$(uname -m)
        dir=restyler-$os-$arch
        ext=tar.gz
        tag=$TAG

        if [[ -z "$tag" ]]; then
          tag=$(gh_release view --json tagName --jq '.tagName')
        fi

        printf 'Release artifact %s/%s.%s\n' "$tag" "$dir" "$ext"

        gh_release download "$TAG" --pattern "$dir.$ext" --output - |
          tar xzf -

        for bin in "$dir"/*; do
          if [ -x "$bin" ]; then
            sudo cp -v "$bin" /usr/local/bin/
          fi
        done

        rm -rf "$dir"
      env:
        GH_TOKEN: ${{ inputs.github-token }}
        TAG: ${{ inputs.tag }}
